---
- name: Install memcached
  pkgng: name={{ item }} state=present
  with_items:
    - memcached

- name: Enable memcached
  service: name=memcached enabled=yes

- name: Start memcached
  service: name=memcached state=started

- name: memcached_flags
  lineinfile:
    dest: /etc/rc.conf
    state: present
    regexp: '^memcached_flags='
    line: 'memcached_flags="{{ memcached_flags }}"'
  notify: restart memcached
  when: memcached_flags is defined
